// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eelogjkpsuhdhjwaidmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbG9namtwc3VoZGhqd2FpZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjAwMjIsImV4cCI6MjA3MjM5NjAyMn0.mqav5IJW5A8n9UoSP8S46-K99zTxiVOdj_rmww6xbkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});